### PR TITLE
Enumerable Methods Solo Project

### PR DESCRIPTION
**Pull request by guirecordon**
For this project, I created methods that imitate the behavior of many of Ruby's Enumerable methods:
I focused my learning on the use of yield with blocks and Procs to write functional code.

I believe it is ready to be reviewed.

Thank you.

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Nice Job :+1: 
You have come a long way given that it's your first attempt with the project. I tried running your code but I got an error: `script.rb:10:in my_each: undefined method each for nil:NilClass (NoMethodError)`
- [x] fix the error and resubmit for another review
- [x] fix the conflicts in this branch
- [x] fix stickler errors and make sure all tests pass 

### Martin Afani

**Comment by guirecordon** [comment]
Thanks, Afani, for the review. It looks like things are working properly now.

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**HI @guirecordon, well done for your efforts on this project:+1:. Let's now fix the following:**
- When no block or argument is given to my_all?, it should return true if none of the elements is false or nil.
Example: `[2, 3, 4].my_all?` should return `true` not `false` and `[false, nil].my_all?` should return `false`. The logic seem to be reversed. Same goes for **when a Regex** is passed and when a pattern that is not a Class or regex is passed as an argument; their logic is reversed.

- When no block or argument is given to my_any?, it should return true **only** if there is at least one element that is not false or nil.
Example: `[nil, false].my_any?` should return `false`

- When a pattern other than a Class or Regex is passed to my_any?, it should return true if there is at least one element that matches that pattern.
Example: `%w[boy, dog, cat].my_any?('dog')` should return `true`

- When a pattern other than a Class or Regex is passed to my_none?, it should return true if **there is no** element that matches that pattern. 
Example: `%w[boy, dog, cat].my_none?('bug')` should return `true` and `%w[boy, dog, cat].my_none?('dog')` should return `false`.


_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

**Comment by guirecordon** [comment]
Thanks, Moses, for the thorough review and comments. I fixed the reverse logic on my_all?, my_any? and my_none methods and they should now be working including with the extra test cases you provided.

**Review by stratospherique — APPROVED** [review]
### Great work implementing the suggested changes :clap: :clap: Congrats, the project is approved :heavy_check_mark: You may merge :+1: :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**

**Comment by guirecordon** [comment]
Thanks, Ahmed!

**Pull request merged**
